Add filter for currency
EnterDAO/LandWorks-FE pull request #217
Opened 2022-02-22 08:26 UTC by zetske

2022-02-22 14:02 UTC, xdemocle submitted a review, later dismissed

2022-02-22 14:03 UTC, xdemocle commented
commits are still missing verification

2022-02-22 16:00 UTC, xdemocle submitted a review, later dismissed

2022-02-23 12:08 UTC, xdemocle requested changes

2022-02-23 12:08 UTC, xdemocle commented on src/modules/land-works/views/explore-view/index.tsx
> +  const [paymentToken, setPaymentToken] = useState(DEFAULT_TOKEN_ADDRESS);
this setPaymentToken and setPaymentTokens and paymentTokens and paymentToken are confusing var names.

consider change paymentToken to paymentTokenSelected for example.

2022-02-23 12:08 UTC, xdemocle commented on src/modules/land-works/views/explore-view/index.tsx
> +  const filteredLands = filterLandsByQuery(lands, searchQuery);
this is not okay. in my explore view im using only one lands and only setLands.

Lands var names `lands` updates based on the AssetsEntity[] we pass.

So, I think is better you wait my imminent PR of today to be merged... so you can take it from there.

2022-02-24 05:53 UTC, zetske commented on src/modules/land-works/views/explore-view/index.tsx
> +  const [paymentToken, setPaymentToken] = useState(DEFAULT_TOKEN_ADDRESS);
This is the variable names used in `list-property-view` but I'll update it

2022-02-24 12:00 UTC, xdemocle commented on src/modules/land-works/components/lands-search/index.tsx
> +    <Search className="search-icon" />
is also a good habit using suffix Icon, ex. SearchIcon in declaring the var name

2022-02-25 13:36 UTC, closed without merging