413 / withdraw loading
EnterDAO/LandWorks-FE pull request #428
Opened 2022-04-01 11:17 UTC by mishaadzh

**Detailed description**:
display loading when tx is going

**Which issue(s) this PR fixes**:
Fixes #413 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2022-04-04 06:49 UTC, failfmi commented
This does not include #386?

2022-04-04 06:49 UTC, failfmi requested changes

2022-04-04 06:49 UTC, failfmi commented on src/modules/land-works/views/single-land-view/index.tsx
> +        localStorage.setItem('WITHDRAW_IN_PROGRESS', asset.metaverseAssetId);
There's a case when you will not withdraw it when you delist it.

2022-04-04 07:50 UTC, mishaadzh commented
> This does not include #386?

I still need to test and I will combine these two tasks

2022-04-05 06:33 UTC, failfmi approved these changes

2022-04-05 06:33 UTC, failfmi commented on src/modules/land-works/views/single-land-view/index.tsx
> +        localStorage.setItem('WITHDRAW_IN_PROGRESS', asset.metaverseAssetId);
There is one more function that withdraws -> `landWorksContract?.withdraw()`

2022-04-05 06:34 UTC, failfmi commented on src/modules/land-works/views/single-land-view/index.tsx
> +        localStorage.setItem('WITHDRAW_IN_PROGRESS', asset.metaverseAssetId);
if the delisting is direct, only then the withdraw should be in progress, if not -> do not set anything in local storage.

2022-04-05 16:40 UTC, failfmi commented on src/modules/land-works/views/single-land-view/index.tsx
> +        localStorage.setItem('WITHDRAW_IN_PROGRESS', asset.metaverseAssetId);
I guess we need to add removal in catch block similar to `delist`?

2022-04-06 07:42 UTC, failfmi approved these changes

2022-04-06 07:42 UTC, failfmi commented on src/modules/land-works/views/my-properties-view/index.tsx
> +  const newProtertyTitle = () => {
one small typo here

2022-04-06 07:42 UTC, failfmi requested changes

2022-04-06 07:42 UTC, failfmi commented on src/modules/land-works/views/my-properties-view/index.tsx
> +  const existProtertyTitle = () => {
one small typo here

2022-04-06 11:07 UTC, failfmi approved these changes

2022-04-06 13:18 UTC, merged