WIP [531] refactoring Rocco
EnterDAO/LandWorks-FE pull request #545
Opened 2022-04-22 08:47 UTC by xdemocle

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2022-04-26 13:33 UTC, xdemocle commented on src/design-system/Modal/modal-styles.ts
> +  background: 'var(--theme-card-color)',
this is not okay.

Into folder desygn-system we use the vars THEME_COLORS.darkBlue03 declared in src/themes/theme-constants.ts.

check  src/themes/theme-constants.ts yo uwill understand

2022-04-26 13:33 UTC, xdemocle commented on src/modules/scene-builder/components/scene-builder-profile/index.tsx
> +            <a style={{ color: 'var(--theme-accent-color)' }} href={builder?.website}>
remove also this. I fixed all a links in global style

2022-04-29 05:52 UTC, failfmi requested changes
The claim modal is broken.

Also, you can compare this version running locally with the latest on develop, and you will notice that some styles might have changed.

2022-04-29 05:52 UTC, failfmi commented on src/components/custom/error-boundary/index.tsx
> +          </div>
What exactly are those?

2022-05-03 10:16 UTC, xdemocle commented on src/components/custom/error-boundary/index.tsx
> +          </div>
moved the svg outside

2022-05-03 10:17 UTC, xdemocle commented
> The claim modal is broken.
> 
> Also, you can compare this version running locally with the latest on develop, and you will notice that some styles might have changed.

Modals have different style now according to Design on Figma. Before they were wrong now they are aligned to Figma that are the same used for metaportal coming from default styling of design-system package

2022-05-03 10:18 UTC, xdemocle commented
@failfmi  The claim modal was also checked and fixed. What other specific UI mistakes you see in that modal?

2022-05-03 12:27 UTC, xdemocle commented
> Price icons on the small cards are padded to the price as well

this fixed

2022-05-04 11:14 UTC, xdemocle commented
> The claim modal is broken.
> 
> Also, you can compare this version running locally with the latest on develop, and you will notice that some styles might have changed.

ok also claim modal is fixed

2022-05-09 06:24 UTC, failfmi approved these changes

2022-05-09 06:24 UTC, merged